### ISSUE TITLE
Create Suricata IDS/IPS

### ISSUE THREAD

**Issue by datboyblu3** [datboyblu3/Vile-The-Purple-Ranger#11]
# Tasks
Install and configure the Suricata IDS/IPS device according to [Wazuh's "Network IDS integration"](https://documentation.wazuh.com/current/proof-of-concept-guide/integrate-network-ids-suricata.html) documentation. 

### Summary:

"Wazuh integrates with a network-based intrusion detection system (NIDS) to enhance threat detection by monitoring network traffic. In this use case, we demonstrate how to integrate Suricata with Wazuh. Suricata can provide additional insights into your network's security with its network traffic inspection capabilities."

- [ ] Install using the Ubuntu 22.04 ISO
- [ ] Install curl
- [ ] Install vim
- [ ] Install inet-tools
- [ ] Install jq
- [ ] Download and extract the Emerging Threats Suricata ruleset
- [ ] Test the IDS functionality

**Comment by datboyblu3** [comment]
## config.yml
![Image](https://github.com/datboyblu3/Vile-The-Purple-Ranger/assets/95729902/b437af54-9d6f-41ad-9312-7a9d8a537f03)

## opensearch.yml
![Image](https://github.com/datboyblu3/Vile-The-Purple-Ranger/assets/95729902/9d1f9a26-38e2-4fc0-9b41-3480068fccf7)
