### ISSUE TITLE
Build Sliver C2 Server

### ISSUE THREAD

**Issue by datboyblu3** [datboyblu3/Vile-The-Purple-Ranger#12]
# Tasks

Sliver [docs](https://sliver.sh/docs) are great for getting up and running

- [x] Download and install [Sliver](https://github.com/BishopFox/sliver)
- [x] Add Sliver to Tailscale environment
- [x] Install Wazuh agent
- [x] Install curl
- [x] Install vim
- [x] Install net-tools
- [x] Install jq
