### ISSUE TITLE
Install pfSense in Proxmox

### ISSUE THREAD

**Issue by datboyblu3** [datboyblu3/Vile-The-Purple-Ranger#3]
# Tasks

- [x] [Download Proxmox](https://pfsense.org/download/)
- [x] [Task 1: Creating a Virtual Machine on Proxmox VE](https://www.zenarmor.com/docs/network-security-tutorials/how-to-install-pfsense-software-on-proxmox#creating-a-virtual-machine-on-proxmox-ve)
- [x] [Task 2: Setting Network Configuration of the pfSense Virtual Machine](https://www.zenarmor.com/docs/network-security-tutorials/how-to-install-pfsense-software-on-proxmox#setting-network-configuration-of-the-pfsense-virtual-machine-on-proxmox-ve)
- [x] [Task 3: Install pfSense](https://www.zenarmor.com/docs/network-security-tutorials/how-to-install-pfsense-software-on-proxmox#installing-pfsense-software)
- [x] [Task 4: Network Device Assignments for pfSense Firewall](https://www.zenarmor.com/docs/network-security-tutorials/how-to-install-pfsense-software-on-proxmox#network-device-assignments-for-pfsense-firewall)
- [x] [Task 5: IP Address Settings for pfSense Firewall](https://www.zenarmor.com/docs/network-security-tutorials/how-to-install-pfsense-software-on-proxmox#ip-address-settings-for-pfsense-firewall)
- [x] [Task 6: Updating pfSense Firewall on CLI](https://www.zenarmor.com/docs/network-security-tutorials/how-to-install-pfsense-software-on-proxmox#updating-pfsense-firewall-on-cli)
- [ ] [Task 7: Accessing the pfSense Web GUI](https://www.zenarmor.com/docs/network-security-tutorials/how-to-install-pfsense-software-on-proxmox#accessing-the-pfsense-web-gui)
