### ISSUE TITLE
Configure Proxmox Server for Remote Access

### ISSUE THREAD

**Issue by datboyblu3** [datboyblu3/Vile-The-Purple-Ranger#4]
## Tasks

- [x] Disable SSH Root access

- [x] Share your pub key with the proxmox local user 

- [x] Create and store proxmox public key on GitHub

- [x] Purchase domain from GoDaddy

- [x] [Remote Access Proxmox GUI ](https://osintteam.blog/use-cloudflare-tunnel-to-securely-expose-your-home-lab-network-to-the-internet-9a181f730e7c)

- [x] [SSH Tailscale](https://dazeb.dev/how-to-access-proxmox-web-gui-remotely-using-ssh/)

**Comment by datboyblu3** [comment]
Can't SSH into server outside of home network

**Comment by datboyblu3** [comment]
Installed Tailscale on proxmox. SSH Tailscale is beta.

**Comment by datboyblu3** [comment]
Tailscale SSH is now live!

**Comment by datboyblu3** [comment]
Tailscale SSH is now available. Check here [Tailscale SSH](https://tailscale.com/kb/1193/tailscale-ssh)

**Comment by datboyblu3** [comment]
At my home, trying to hit the private IP of the Wazuh dashboard but can't. I will have to edit the /etc/wazuh-dashboard/opensearch_dashboards.yml file to include the private IP. Probably set the server.host field to 0.0.0.0 so it accepts all available IPs.

**Comment by datboyblu3** [comment]
## Wazuh Indexer Config
![Image](https://github.com/datboyblu3/Vile-The-Purple-Ranger/assets/95729902/dd4ee300-e08c-4f09-a2da-29bd8dd0f9e4)

## Wazuh Indexer Opensearch
![Image](https://github.com/datboyblu3/Vile-The-Purple-Ranger/assets/95729902/4a72d7d4-839b-4c75-9493-db888ce43c8f)

### Wazuh Manager/Server Filebeat Config
![Image](https://github.com/datboyblu3/Vile-The-Purple-Ranger/assets/95729902/33d6a01d-9ca4-4d4d-a240-c9e31e3bb6f5)

**Comment by datboyblu3** [comment]
Can access Proxmox server via tailscale. Will probably have to route traffic through an exit node to access the wazuh servers. As for now, the proxmox server can be accessed remotely.
