### ISSUE TITLE
Configure & Deploy Proxmox VMs with Terraform

### ISSUE THREAD

**Issue by datboyblu3** [datboyblu3/Vile-The-Purple-Ranger#8]
# Tasks

- [x] Create SSH Keys
- [ ] Connect Proxmox and Terraform using Provider and API
    - [x] [Encrypt secret keys in Terraform code](https://youtu.be/3N0tGKwvBdA?si=D9WtaGownCGalMn0&t=848)
    - [ ] Configure AWS Key Management to store the API secret token 
- [ ] Create a Cloud-Init Base
- [ ] [Create pfSense VM](https://www.zenarmor.com/docs/network-security-tutorials/how-to-install-pfsense-software-on-proxmox)

#### Articles by Fatzombi

- [Deploying your VMs with Terraform Pt. 1](https://medium.com/@fat_zombi/automating-your-homelab-with-proxmox-cloud-init-terraform-and-ansible-part-1-configuring-a-448576621edd)

- [Deploying your VMs with Terraform Pt. 2](https://medium.com/@fat_zombi/automating-your-homelab-with-proxmox-cloud-init-terraform-and-ansible-part-2-deploying-your-a7de6caa64b7)

- [Deploying your VMs with Terraform Pt. 3](https://medium.com/@fat_zombi/automating-your-homelab-with-proxmox-cloud-init-terraform-and-ansible-part-3-automating-with-23acc2343340)

#### Articles by Kevin Summers

- [Terraform: Deploy VM to Proxmox](https://medium.com/geekculture/deploy-a-virtual-machine-to-proxmox-with-terraform-733301842f1a)

- [Connect Proxmox and Terraform using Provider and API](https://medium.com/geekculture/connect-proxmox-and-terraform-using-provider-and-api-854a91f4b65d)

- [Create a Cloud-Init Base Image for Ubuntu in Proxmox with Bash](https://medium.com/geekculture/create-a-cloud-init-base-image-for-ubuntu-in-proxmox-with-bash-b392310dace5)

### Cloud Init References

- [Terraform Cloud Init Official Docs](https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/guides/cloud_init)
- [Cloud Init w/ Proxmox](https://pve.proxmox.com/wiki/Cloud-Init_FAQ#Creating_a_custom_cloud_image)
