### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by datboyblu3** [datboyblu3/Vile-The-Purple-Ranger#9]
# Task Build a Kali VM in Proxmox

- [ ] [Download VM]()
- [ ] [Add VM to Tailscale Environment]()
- [ ] [Install necessary tools]()
- [ ] [Install Sliver C2 server]()
- [ ] [Task 4]()
- [ ] [Task 5]()
